- name: install python-virtualenv
  yum:
    name: >-
      {%- if ansible_distribution_major_version >= '8' -%} python3-virtualenv
      {%- else -%} python-virtualenv
      {%- endif -%}

# libvirt-devel is not necessary on the VirtualBox environment
- name: install libvirt-devel
  yum:
    name: libvirt-devel
  when: VBMC_HYPERVISOR == 'libvirt'

- name: checkout virtualbmc (vbox patched version)
  shell: |
    git clone https://github.com/kskmori/virtualbmc-vbox
    cd virtualbmc-vbox
    git checkout {{ VBMC_VERSION }}
  become: false

- name: create virtual env
  shell: |
    virtualenv {{ VBMC_VENV_DIR }}
    . {{ VBMC_VENV_DIR }}/bin/activate
    pip install --upgrade pip
    pip install -e ./virtualbmc-vbox/
    deactivate
  become: false

- name: firewalld zone
  set_fact:
    FIREWALLD_OPTS: --zone=libvirt
  when: VBMC_HYPERVISOR == 'libvirt' and ansible_distribution_major_version >= '8'
  tags: firewall

- name: firewalld to allow 623/udp
  command: firewall-cmd --add-port=623/udp {{ FIREWALLD_OPTS|default('') }}
  register: result
  changed_when: '"ALREADY_ENABLED" not in result.stderr'
  tags: firewall

- name: firewalld to allow 623/udp (permanent)
  command: firewall-cmd --permanent --add-port=623/udp {{ FIREWALLD_OPTS|default('') }}
  register: result
  changed_when: '"ALREADY_ENABLED" not in result.stderr'
  tags: firewall
